/* The page frame: header, the synthetic-data banner when the file says so, the
   toolbar with its chips, the table, and whichever modal is open. Everything
   below the toolbar is a pure function of `state` and the benchmark: the grid
   is computed once per (dataset, view, metric), the scores once per grid and
   visible rows, and the column order from the section the reader picked. */

import { useMemo } from 'react';
import {
  BENCH,
  BENCH_ERROR,
  allChipTags,
  computeGrid,
  datasetById,
  metricFor,
  orderResults,
  sectionScores,
  visibleRows,
  type Grid,
  type Section,
  type SectionScores,
} from '../../entities/results';
import { useBenchShortcuts, useBenchState, type BenchEnv } from '../../shared/model';
import { FullGraphModal } from '../../widgets/curve-graph/FullGraphModal';
import { CellDetailModal } from '../../widgets/detail/CellDetailModal';
import { HeaderDetailModal } from '../../widgets/detail/HeaderDetailModal';
import { BenchHeader } from '../../widgets/header/BenchHeader';
import { ResultsTable } from '../../widgets/results-table';
import { Toolbar } from '../../widgets/toolbar/Toolbar';

const EMPTY_TAGS: ReadonlySet<string> = new Set();

export function BenchPage() {
  // Stable for the lifetime of the page: results.json is a build input.
  const env = useMemo<BenchEnv>(
    () => ({
      datasets: BENCH?.datasets.map((d) => d.id) ?? [],
      defaultDataset: BENCH?.defaultDataset ?? null,
      tagsFor: (id) => {
        const d = datasetById(id);
        return d ? allChipTags(d.family) : EMPTY_TAGS;
      },
      rowsFor: (id) => new Set(datasetById(id)?.family.queries.map((q) => q.id) ?? []),
    }),
    [],
  );
  const [state, dispatch] = useBenchState(env);
  useBenchShortcuts(state, dispatch);

  const dataset = datasetById(state.dataset ?? BENCH?.defaultDataset);
  const metric = metricFor(state.view, state.latencyMetric);
  const grid: Grid | null = useMemo(() => (dataset ? computeGrid(dataset, state.view, metric) : null), [dataset, state.view, metric]);
  const rows = useMemo(() => (dataset ? visibleRows(dataset.family, state.chips) : []), [dataset, state.chips]);
  const scores = useMemo<Record<Section, SectionScores> | null>(() => {
    if (!dataset || !grid) return null;
    return {
      nofilter: sectionScores(grid, dataset.results, rows.filter((r) => r.section === 'nofilter'), 'nofilter'),
      filtered: sectionScores(grid, dataset.results, rows.filter((r) => r.section === 'filtered'), 'filtered'),
    };
  }, [dataset, grid, rows]);
  const results = useMemo(() => (dataset && scores ? orderResults(dataset.results, scores[state.sortSection]) : []), [dataset, scores, state.sortSection]);

  if (!BENCH || !dataset || !grid || !scores) {
    return (
      <div className="vb-app">
        <BenchHeader />
        <div className="err">
          {BENCH_ERROR ? (
            <>
              <div>The results file could not be read.</div>
              <code>{BENCH_ERROR.message}</code>
            </>
          ) : (
            <div>
              No results yet. Run a participant, then <code>vectorbench assemble</code> and <code>npm run build</code> in <code>frontend/</code>.
            </div>
          )}
        </div>
      </div>
    );
  }

  const detail = state.detail;
  const detailResult = detail?.kind === 'cell' ? dataset.results.find((r) => r.id === detail.pid) : undefined;
  const detailRow = detail?.kind === 'cell' ? dataset.family.queries.find((q) => q.id === detail.qid) : undefined;

  return (
    <div className="vb-app">
      <BenchHeader />
      {BENCH.sample && (
        <div className="banner" data-role="sample-banner">
          <b>synthetic sample</b>
          <span>
            Every number on this page was generated by <code>frontend/scripts/sample-results.mjs</code> to exercise the page; nothing was measured.{' '}
            <code>vectorbench assemble</code> replaces <code>results.json</code> with real results.
          </span>
        </div>
      )}
      <Toolbar bench={BENCH} dataset={dataset} state={state} dispatch={dispatch} />
      <ResultsTable dataset={dataset} results={results} rows={rows} grid={grid} scores={scores} state={state} dispatch={dispatch} />
      {state.graphRows && <FullGraphModal dataset={dataset} results={results} grid={grid} state={state} dispatch={dispatch} />}
      {detail?.kind === 'header' && <HeaderDetailModal dataset={dataset} results={results} row={detail.row} dispatch={dispatch} />}
      {detail?.kind === 'cell' && detailResult && detailRow && (
        <CellDetailModal dataset={dataset} result={detailResult} row={detailRow} state={state} dispatch={dispatch} />
      )}
    </div>
  );
}
